
import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Aguiar Cleaning Service",
  description: "Generated by create Claudio Bispo",
};

import Navbar from "./Navbar/page";
import Footer from "./Footer/page";


interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
