
import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Aguiar Cleaning Service",
  description: "Generated by create Claudio Bispo",
};

import Navbar from "./Navbar/page";

// Definição do tipo para os links do menu
interface MainMenuLink {
  url: string;
  label: string;
}

const mainMenuLinks: MainMenuLink[] = [
  { url: 'home', label: 'Home' },
  { url: 'company', label: 'Company' },
  { url: 'services', label: 'Services' },
  { url: 'quote', label: 'Quote' },
  { url: 'feedback', label: 'Feedback' },
  { url: 'contact', label: 'Contact' }
];


interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar mainMenuLinks={mainMenuLinks} />
        {children}
        </body>
    </html>
  );
}
